#!/usr/bin/env ruby
# ^syntax detection
#
# PLUGIN DETECTION
#
%w(vagrant-berkshelf vagrant-lxc).each do |plugin|
  fail "#{plugin} not found, exiting." unless Vagrant.has_plugin?(plugin)
end
#
# NODE CONFIGURATION
#
nodes =
  [{
    name:      'master01',
    ipaddress: '172.18.1.10',
    run_list:  ['recipe[mesos::master]']
  }, {
    name:      'slave01',
    ipaddress: '172.18.2.10',
    run_list:  ['recipe[mesos::slave]']
  }]
#
# VAGRANT CONFIGURATION
#
Vagrant.configure(2) do |config|
  # LXC box from Atlas
  config.vm.box = 'fgrehm/centos-6-64-lxc'
  # Set up nodes
  nodes.each do |node|
    config.vm.define node[:name] do |v|
      # Set up hostname
      v.vm.hostname = node[:name]
      # Connnect to private network
      v.vm.network 'private_network', ip: node[:ipaddress], netmask: '255.255.0.0', lxc__bridge_name: 'virbr0'
      # Provision with Chef
      v.vm.provision :chef_zero do |chef|
        chef.nodes_path = ''
        chef.run_list   = node[:run_list]
      end
    end
  end
end
