#!/usr/bin/env ruby
# ^syntax detection
#
# NODE CONFIGURATION
#
nodes =
  [{
    name:      'master01',
    ipaddress: '172.18.0.1',
    run_list:  ['recipe[apt]', 'recipe[mesos::master]']
  }, {
    name:      'slave01',
    ipaddress: '172.18.1.1',
    run_list:  ['recipe[apt]', 'recipe[mesos::slave]']
  }]
#
# VAGRANT CONFIGURATION
#
Vagrant.configure(2) do |config|
  # LXC box from ATLAS
  config.vm.box = 'debian/jessie64'
  # Berkshelf
  config.berkshelf.enabled        = true
  config.berkshelf.berksfile_path = './Berksfile'
  # Set up nodes
  nodes.each do |node|
    config.vm.define node[:name] do |v|
      # Set up hostname
      v.vm.hostname = node[:name]
      # Connnect to private network
      v.vm.network 'private_network', ip: node[:ipaddress],
                                      netmask: '255.255.0.0',
                                      lxc__bridge_name: 'virbr0'
      # Install lsb-release for Ohai
      v.vm.provision :shell, inline: 'apt-get -y install lsb-release'
      # Provision with Chef
      v.vm.provision :chef_zero do |chef|
        chef.run_list = node[:run_list]
      end
    end
  end
end
